### ISSUE TITLE
4K 视界一直提示 Cookie 失效

### ISSUE THREAD

**Issue by ChangeHow** [Alexecz/hao4k-checkin-nodejs#11]
如题，签到的时候一直提示 Cookie 失效，但是我已经更新了 Cookie

**Comment by coldcrocodilecc** [comment]
我也是，hao4k正常签到，4k视界提示 Cookie 失效

**Comment by watilion** [comment]
pc端好像服务器添加了校验，原有的方式无法进行签到了，我修改了代码尝试使用移动端地址进行签到，已创建pr，你们可以尝试一下

**Comment by ColdBeanSprouts** [comment]
谢谢！

**Comment by Alexecz** [comment]
感谢watilion大佬，已经merge进来了
