### ISSUE TITLE
签到失败

### ISSUE THREAD

**Issue by fgym666** [Alexecz/hao4k-checkin-nodejs#17]
4K视界: 签到出错或超时Error: Unexpected close tag
Line: 8
Column: 7
Char: >* hao4K: 获取formhash出错Error: connect ETIMEDOUT 1.62.64.108:443

**Comment by YTB-X** [comment]
网站添加了人机认证，估计不好搞了

**Comment by Alexecz** [comment]
这网站反复横跳 有人机认证了就手动签到一段时间吧

**Comment by fgym666** [comment]
hao4k网页签到9.14号关闭了..........
