### ISSUE TITLE
hao4K签到成功，4k视界签到失败

### ISSUE THREAD

**Issue by angus9487** [Alexecz/hao4k-checkin-nodejs#4]
hao4K 获取用户信息成功！
hao4K  本次签到K币奖励： 3 个； 已连续签到： 15 天; 今日排名： 675 位； 签到总天数： 74 天；
4K视界: 签到失败！hao4K: 签到失败！ * 4K视界: 获取formhash出错Error: Request failed with status code 403* hao4K:  本次签到K币奖励： 3 个； 已连续签到： 15 天; 今日排名： 675 位； 签到总天数： 74 天；

**Comment by Alexecz** [comment]
加验证了，先手动签到4k视界吧
