### ISSUE TITLE
hao4k提示出错。。。

### ISSUE THREAD

**Issue by fgym666** [Alexecz/hao4k-checkin-nodejs#7]
4K视界: 今日已签！ 本次签到奖励： 3 个币； 已连续签到： 1 天; 今日排名： 6244 位； 签到总天数： 149 天；* hao4K: 获取formhash出错Error: connect ETIMEDOUT 113.1.0.33:443

**Comment by Alexecz** [comment]
hao4k容易网络连接超时，手动一下吧

**Comment by Alexecz** [comment]
更新一下仓库，应该能解决出错了
